# Generated by Django 2.1.4 on 2019-03-15 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el')),
                ('field', models.CharField(max_length=150, null=True, verbose_name='Campo')),
                ('before_char', models.CharField(blank=True, max_length=500, null=True, verbose_name='Texto anterior')),
                ('after_char', models.CharField(blank=True, max_length=500, null=True, verbose_name='Texto posterior')),
                ('before_text', models.TextField(blank=True, null=True, verbose_name='Texto largo anterior')),
                ('after_text', models.TextField(blank=True, null=True, verbose_name='Texto largo posterior')),
                ('before_id', models.IntegerField(blank=True, null=True, verbose_name='Id anterior')),
                ('after_id', models.IntegerField(blank=True, null=True, verbose_name='Id posterior')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_formlog_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='form',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='form',
            name='active',
            field=models.BooleanField(default=True, help_text='Indica si el modelo está operativo', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='form',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='form',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Eliminado el'),
        ),
        migrations.AlterField(
            model_name='form',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AddField(
            model_name='formlog',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form.Form', verbose_name='Formulario'),
        ),
    ]
