# Generated by Django 2.1.4 on 2019-03-15 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20190315_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formlog',
            old_name='form',
            new_name='record',
        ),
    ]
