# Generated by Django 2.1.7 on 2019-04-01 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0003_auto_20190315_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formlog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='formlog',
            name='record',
        ),
        migrations.RemoveField(
            model_name='form',
            name='active',
        ),
        migrations.AddField(
            model_name='form',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_form_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AlterField(
            model_name='form',
            name='color',
            field=models.CharField(blank=True, default='#001a7b', max_length=10, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='form',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='form',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha eliminación'),
        ),
        migrations.AlterField(
            model_name='form',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.DeleteModel(
            name='FormLog',
        ),
    ]
